"use client"; // this makes it a client component

import { useState, useEffect } from "react";
import CalculatorLayout from "../CalculatorLayout"; // adjust path if needed

const NetOperatingIncomeCalculator: React.FC = () => {
  const [grossIncome, setGrossIncome] = useState<number>(0);
  const [operatingExpenses, setOperatingExpenses] = useState<number>(0);
  const [noi, setNOI] = useState<number | null>(null);

  const calculateNOI = () => {
    setNOI(grossIncome - operatingExpenses);
  };

  return (
    <CalculatorLayout
      title="Net Operating Income Calculator"
      description="Calculate the Net Operating Income (NOI) of your property to assess profitability and investment potential."
      seoContent={
        <>
          <h2 className="text-2xl font-semibold">Maximize Your Property Investment Returns</h2>
          <p>
            Net Operating Income (NOI) is a fundamental metric in real estate investing, representing the total revenue generated by a property minus all operating expenses, excluding financing and taxes. Calculating NOI provides insight into the true profitability of a rental or commercial property and helps investors make informed decisions.
          </p>
          <p>
            Understanding your NOI allows you to compare different properties, assess potential cash flow, and evaluate your investment's risk and return profile. It's also a critical input when calculating capitalization rates (Cap Rate), which are widely used to determine the value and attractiveness of income-producing properties.
          </p>
          <p>
            The formula for NOI is simple yet powerful:
          </p>
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 text-center font-mono text-sm sm:text-base my-4">
            NOI = Gross Income − Operating Expenses
          </div>
          <p>
            Gross income includes all rental income, ancillary fees, and other property-related revenue streams. Operating expenses cover property management fees, maintenance, utilities, insurance, and taxes. By excluding mortgage payments and financing costs, NOI reflects the property's operational efficiency.
          </p>
          <p>
            High NOI indicates a profitable property and efficient management, while a low NOI signals potential issues or underperformance. Investors can use NOI to assess whether a property meets their investment criteria and to make comparisons across multiple opportunities.
          </p>
          <p>
            Tracking NOI over time also helps owners and managers identify trends, optimize expenses, and implement strategies to improve revenue. By analyzing NOI in conjunction with other key metrics like occupancy rate, rental yield, and cash-on-cash return, you gain a comprehensive view of a property's performance.
          </p>
          <p>
            This calculator allows property investors, landlords, and real estate professionals to quickly determine the net operating income for any property. Input your total income and operating expenses to see instant results, enabling smarter financial planning and better investment decisions.
          </p>
          <p>
            Use this tool to evaluate potential acquisitions, manage existing properties, and communicate financial performance to stakeholders, lenders, or partners. Accurate NOI calculation is a cornerstone of successful property investment.
          </p>
        </>
      }
    >
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <label className="block text-gray-700 font-semibold mb-1">Gross Income ($)</label>
          <input
            type="number"
            value={grossIncome || ""}
            onChange={(e) => setGrossIncome(parseFloat(e.target.value) || 0)}
            className="w-full border rounded-lg p-2 focus:ring-2 focus:ring-blue-400"
          />
        </div>
        <div>
          <label className="block text-gray-700 font-semibold mb-1">Operating Expenses ($)</label>
          <input
            type="number"
            value={operatingExpenses || ""}
            onChange={(e) => setOperatingExpenses(parseFloat(e.target.value) || 0)}
            className="w-full border rounded-lg p-2 focus:ring-2 focus:ring-blue-400"
          />
        </div>
      </div>

      <div className="text-center mt-8">
        <button
          onClick={calculateNOI}
          className="px-8 py-3 bg-blue-600 text-white font-bold rounded-lg shadow-lg hover:bg-blue-700 transition"
        >
          Calculate NOI
        </button>
      </div>

      {noi !== null && (
        <div className="text-center mt-8 bg-green-50 p-6 rounded-xl">
          <h3 className="text-gray-700 font-medium">Net Operating Income</h3>
          <p className="text-3xl font-bold text-green-700">${noi.toFixed(2)}</p>
        </div>
      )}
    </CalculatorLayout>
  );
};

export default NetOperatingIncomeCalculator;